name: Build ReactJS App
description:  Reusable action to build a ReactJS App

runs:
  using: composite
  steps:
    - name: Build ReactJS App
      shell: bash
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm cache clean --force
        npm install --save-dev web-vitals
        npm install
        npm run build
