name: Build ReactJS App
description:  Reusable action to build a ReactJS App

runs:
  using: composite
  steps:
    - name: Build ReactJS App
      shell: bash
      run: |
        npm install
        npm run build
