name: Pull Request

on: # trigger conditions
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: write

jobs:
  ci:
    name: "🔍 Check"
    uses: vti-do2402/cicd-core/.github/workflows/ci-maven.yml@main
    with:
      runs_on: ${{ vars.RUNS_ON }}
      distribution: ${{ vars.JAVA_DISTRIBUTION }}
      java_version: ${{ vars.JAVA_VERSION }}
      skip_sonar: true
      artifacts: database-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
